services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: oh-referral-app-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
      - WATCHPACK_POLLING=true
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:5000/api
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    container_name: oh-referral-app-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=your_root_password
      - DB_NAME=your_database_name
      - JWT_SECRET=ohr_super_secret_jwt_key_2026
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: oh-referral-app-db
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database_name
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: